{% set name = "siphash24" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/siphash24-{{ version }}.tar.gz
  sha256: 242d6901a81260f618938635a25ae7f208e744f7ee6c571f1b255c1c4c62917d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c')}}
    - meson >=1.0.0                        # [build_platform != target_platform]
    - cython >=3.0.2  # [build_platform != target_platform]
    - meson-python >=0.14.0  # [build_platform != target_platform]
  host:
    - python
    - cython >=3.0.2
    - meson >=1.0.0
    - meson-python >=0.14.0
    - pip
  run:
    - python

test:
  imports:
    - siphash24
  commands:
  - "PYTHONHASHSEED=0 python check.py"
  - python test.py
  source_files:
  - test.py
  - check.py
  requires:
    - pip

about:
  summary: Streaming-capable SipHash-1-3 and SipHash-2-4 Implementation
  home: https://github.com/dnicolodi/python-siphash24/
  dev_url: https://github.com/dnicolodi/python-siphash24/
  license: 'Apache-2.0 or LGPL-2.1-or-later'
  license_file:
  - LICENSES/Apache-2.0.txt
  - LICENSES/LGPL-2.1-or-later.txt

extra:
  recipe-maintainers:
    - inducer
    - matthiasdiener
